version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: max-bucket-gallery-mongodb
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - db:/data/db

volumes:
  db:
