export const IMAGES_FETCH = 'IMAGES/FETCH';
export const IMAGES_FETCH_SUCCESS = 'IMAGES/FETCH_SUCCESS';
export const IMAGES_FETCH_FAIL = 'IMAGES/FETCH_FAIL';
export const IMAGES_DELETE = 'IMAGES/DELETE';
export const IMAGES_DELETE_SUCCESS = 'IMAGES/DELETE_SUCCESS';
export const IMAGES_DELETE_FAIL = 'IMAGES/DELETE_FAIL';
