export const USER_LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER/LOGIN_FAIL';
export const USER_REGISTER_SUCCESS = 'USER/REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER/REGISTER_FAIL';
export const USER_LOGOUT = 'USER/LOGOUT';
export const USER_UPDATE_SUCCESS = 'USER/USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER/USER_UPDATE_FAIL';
